### ISSUE TITLE
能否检查一下有没有两个使用到的framework是否上传!

### ISSUE THREAD

**Issue by wangzhao0630** [Rainbow-CPaaS/Rainbow-iOS-SDK-Samples#7]
![CEF0168506D1FD8416C6BBB110D5ED43](https://user-images.githubusercontent.com/16663316/69796341-d1602980-1208-11ea-8bd2-607ec8fc97f7.jpg) 没有找到相关framework的文件在本地

**Comment by wangzhao0630** [comment]
![E614B80D47574022FB4718210E08EB75](https://user-images.githubusercontent.com/16663316/69796510-22701d80-1209-11ea-878a-08280b969564.jpg)

**Comment by wangzhao0630** [comment]
I find this href :https://sdk.openrainbow.io/ios/carthage/RainbowSDK.json and download it success

**Comment by vyskocil** [comment]
Hi @wangzhao0630 ! 
Please look at [Getting Started](https://hub.openrainbow.com/#/documentation/doc/sdk/ios/lts/guides/Getting_Started) guide, it explained where to look for the Rainbow SDK and how to install it.
